---
# Source: applications/templates/helm-guestbook.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/Kalimero66/argocd-example-apps
    targetRevision: HEAD
    helm:
      releaseName: demo-dev
      valueFiles:
      - values-production.yaml
